from ai_guardrail.domain import EntityType

V2_CATALOG: dict[str, dict[EntityType, tuple[str, ...]]] = {
    "train": {
        EntityType.PERSON: (
            "maya chen",
            "Maya Chen",
            "DANIEL KIM",
            "lena ortiz",
            "Lena Ortiz",
            "Victor Hale",
            "nora singh",
            "Omar Blake",
        ),
        EntityType.ADDRESS: (
            "14 Birch Row, Alderwick",
            "208 Summit Drive, Brookmere",
            "5 Copper Lane, Fairhaven",
            "91 Meadow Court, Glenford",
            "33 River Walk, Highcrest",
            "760 Aspen Road, Ivydale",
            "2 Beacon Street, Kingswell",
            "48 Clover Avenue, Longmere",
        ),
        EntityType.EMAIL: (
            "maya.chen@example.test",
            "482901@example.test",
            "daniel_kim@example.test",
            "lena-ortiz@example.test",
            "ops.owner@example.test",
            "700314@example.test",
            "nora.singh@example.test",
            "omar.blake@example.test",
        ),
        EntityType.API_KEY: (
            "sk-v2-A7B8C9D0E1F2G3H4",
            "api_v2_Q1W2E3R4T5Y6U7I8",
            "pk-v2-9081726354453627",
            "key v2 A1C3 E5G7 I9K2 M4O6",
            "tok_v2_4R5T6Y7U8I9O0P1A",
            "sk-v2-Z9X8C7V6B5N4M3L2",
            "api-v2-1122-3344-5566-7788",
            "sec_v2_H8J7K6L5P4O3I2U1",
        ),
        EntityType.CUSTOMER_ID: (
            "654321",
            "802417",
            "CUST-24680",
            "ACCT-73195",
            "customer_519204",
            "CID-88426",
            "390175",
            "CLIENT-62048",
        ),
        EntityType.INTERNAL_PROJECT: (
            "Project Quartz",
            "project Cedar",
            "PROJECT NOVA",
            "Project Bluejay",
            "project atlas",
            "PROJECT HARBOR",
            "Project Mosaic",
            "project Kestrel",
        ),
    },
    "validation": {
        EntityType.PERSON: (
            "sophia ng",
            "Sophia Ng",
            "ETHAN COLE",
            "ravi mehta",
            "Ravi Mehta",
            "Grace Lin",
            "tessa ward",
            "Julian Frost",
        ),
        EntityType.ADDRESS: (
            "67 Elm Passage, Marlowe",
            "310 Ridge Avenue, Norhaven",
            "8 Poppy Close, Oakridge",
            "125 Quarry Street, Pinehurst",
            "44 Seabrook Lane, Queensport",
            "902 Terrace Way, Rosefield",
            "16 Union Road, Silverbrook",
            "73 Valley Court, Thornwick",
        ),
        EntityType.EMAIL: (
            "sophia.ng@example.test",
            "593028@example.test",
            "ethan_cole@example.test",
            "ravi-mehta@example.test",
            "release.owner@example.test",
            "814602@example.test",
            "tessa.ward@example.test",
            "julian.frost@example.test",
        ),
        EntityType.API_KEY: (
            "sk-val-B6C7D8E9F0G1H2J3",
            "api_val_R2T3Y4U5I6O7P8A9",
            "pk-val-8172635445362718",
            "key val B2D4 F6H8 J1L3 N5P7",
            "tok_val_5T6Y7U8I9O0P1A2S",
            "sk-val-X8C7V6B5N4M3L2K1",
            "api-val-2233-4455-6677-8899",
            "sec_val_J9K8L7P6O5I4U3Y2",
        ),
        EntityType.CUSTOMER_ID: (
            "715942",
            "936208",
            "CUST-35791",
            "ACCT-84206",
            "customer_620315",
            "CID-99537",
            "401286",
            "CLIENT-73159",
        ),
        EntityType.INTERNAL_PROJECT: (
            "Project Saffron",
            "project Delta",
            "PROJECT SUMMIT",
            "Project Kingfisher",
            "project beacon",
            "PROJECT TIDELINE",
            "Project Canvas",
            "project Wren",
        ),
    },
    "challenge": {
        EntityType.PERSON: (
            "alicia ford",
            "Alicia Ford",
            "MARTIN SHAW",
            "keira patel",
            "Keira Patel",
            "Hugo Mills",
            "selene cruz",
            "Isaac Stone",
        ),
        EntityType.ADDRESS: (
            "29 Walnut Mews, Umberton",
            "406 Winding Road, Valehurst",
            "11 Yarrow Lane, Westmere",
            "150 Zenith Street, Yorkhaven",
            "52 Amber Court, Ashcombe",
            "621 Bramble Way, Bellford",
            "7 Cypress Row, Coldwater",
            "84 Dovetail Avenue, Dunwich",
        ),
        EntityType.EMAIL: (
            "alicia.ford@example.test",
            "625139@example.test",
            "martin_shaw@example.test",
            "keira-patel@example.test",
            "delivery.owner@example.test",
            "927415@example.test",
            "selene.cruz@example.test",
            "isaac.stone@example.test",
        ),
        EntityType.API_KEY: (
            "sk-chal-C5D6E7F8G9H0J1K2",
            "api_chal_T3Y4U5I6O7P8A9S0",
            "pk-chal-7263544536271829",
            "key chal C3E5 G7I9 K2M4 O6Q8",
            "tok_chal_6Y7U8I9O0P1A2S3D",
            "sk-chal-C7V6B5N4M3L2K1J0",
            "api-chal-3344-5566-7788-9900",
            "sec_chal_K0L9P8O7I6U5Y4T3",
        ),
        EntityType.CUSTOMER_ID: (
            "826053",
            "147319",
            "CUST-46802",
            "ACCT-95317",
            "customer_731426",
            "CID-10648",
            "512397",
            "CLIENT-84260",
        ),
        EntityType.INTERNAL_PROJECT: (
            "Project Topaz",
            "project Elm",
            "PROJECT VISTA",
            "Project Sandpiper",
            "project compass",
            "PROJECT MOONRISE",
            "Project Fresco",
            "project Heron",
        ),
    },
}
