from ai_guardrail.synthetic.templates import Template


def _templates(split: str, stems: tuple[str, ...]) -> tuple[Template, ...]:
    return tuple(
        Template(
            family=f"v2-{split}-{index:02d}",
            split=split,
            text=text,
        )
        for index, text in enumerate(stems, start=1)
    )


V2_TEMPLATES = (
    *_templates(
        "train",
        (
            "Send the file for {PERSON}, customer {CUSTOMER_ID}, to {INTERNAL_PROJECT}.",
            "Could {PERSON} confirm the contact email {EMAIL}?",
            "The delivery destination is {ADDRESS}.",
            "Rotate {API_KEY} before the next {INTERNAL_PROJECT} review.",
            "Please investigate customer number {CUSTOMER_ID}.",
            "Prepare a concise update about {INTERNAL_PROJECT}.",
            "Email {PERSON} using {EMAIL} after the review.",
            "Account {CUSTOMER_ID} lists the mailing address {ADDRESS}.",
            "Replace the temporary credential {API_KEY}.",
            "Share the {INTERNAL_PROJECT} summary with {EMAIL}.",
            "The owner is {PERSON}; their address is {ADDRESS}.",
            "Customer {CUSTOMER_ID} requested replies at {EMAIL}.",
            "Ask {PERSON} to join the {INTERNAL_PROJECT} briefing.",
            "Move {API_KEY} into the vault entry for customer {CUSTOMER_ID}.",
            "Route the package to {ADDRESS} and notify {EMAIL}.",
            "Account holder: {PERSON}\nCustomer number: {CUSTOMER_ID}.",
            "The project status is amber and 30 of 50 tasks are complete.",
            "The word apex describes the highest point of the shape.",
            "Build 482901 passed version 7.4.2 without warnings.",
            "Please check the local file owner.name and the draft domain example.",
        ),
    ),
    *_templates(
        "validation",
        (
            "Archive {PERSON}'s profile for account {CUSTOMER_ID} under {INTERNAL_PROJECT}.",
            "Reach {PERSON} at the verified mailbox {EMAIL}.",
            "Use this shipping location: {ADDRESS}.",
            "Invalidate credential {API_KEY} after closing {INTERNAL_PROJECT}.",
            "What is the current state of client identifier {CUSTOMER_ID}?",
            "Draft the weekly note for {INTERNAL_PROJECT}.",
            "Notify {PERSON}; the approved address is {EMAIL}.",
            "The address on customer {CUSTOMER_ID} is {ADDRESS}.",
            "Remove the expired token {API_KEY} from configuration.",
            "Forward the plan for {INTERNAL_PROJECT} to {EMAIL}.",
            "Delivery contact {PERSON} can be found at {ADDRESS}.",
            "Link customer {CUSTOMER_ID} with mailbox {EMAIL}.",
            "Invite {PERSON} to tomorrow's {INTERNAL_PROJECT} checkpoint.",
            "Audit {API_KEY} against the record for {CUSTOMER_ID}.",
            "Confirm {ADDRESS}, then send the receipt to {EMAIL}.",
            "Profile owner: {PERSON}\nReference: {CUSTOMER_ID}.",
            "This project contains 12 milestones and 4 delayed tasks.",
            "A summit is the highest part of a hill or mountain.",
            "Release 593028 targets build 8.5.3 for tomorrow.",
            "The filename release.owner and host example are incomplete.",
        ),
    ),
    *_templates(
        "challenge",
        (
            "Move {PERSON}'s case {CUSTOMER_ID} into the workspace for {INTERNAL_PROJECT}.",
            "The callback contact is {PERSON} at {EMAIL}.",
            "Confirm that the destination remains {ADDRESS}.",
            "Retire {API_KEY} when the {INTERNAL_PROJECT} demo finishes.",
            "Look up the history for account reference {CUSTOMER_ID}.",
            "Summarize recent decisions from {INTERNAL_PROJECT}.",
            "Write to {PERSON} through {EMAIL} with the result.",
            "Customer {CUSTOMER_ID} recently moved to {ADDRESS}.",
            "Quarantine the exposed test key {API_KEY}.",
            "Send the {INTERNAL_PROJECT} digest to {EMAIL}.",
            "Courier contact {PERSON} receives mail at {ADDRESS}.",
            "Associate identifier {CUSTOMER_ID} with contact {EMAIL}.",
            "Have {PERSON} approve the {INTERNAL_PROJECT} memo.",
            "Compare {API_KEY} with the secret for {CUSTOMER_ID}.",
            "Deliver to {ADDRESS}; provide tracking at {EMAIL}.",
            "Named contact: {PERSON}\nAccount reference: {CUSTOMER_ID}.",
            "Project planning lists 18 tasks and 6 unresolved risks.",
            "A vista is a pleasing view seen through a long opening.",
            "Job 625139 completed against release 9.6.4.",
            "The username delivery.owner is not a complete email address.",
        ),
    ),
)


V2_PREFIXES: dict[str, tuple[str, ...]] = {
    "train": (
        "",
        "Please ",
        "Today, ",
        "For the support queue, ",
        "Quick request: ",
        "In the case notes, ",
        "Before noon, ",
        "For audit preparation, ",
        "The operator wrote: ",
        "During triage, ",
        "For the account team, ",
        "In this message, ",
        "As a follow-up, ",
        "For tomorrow's handoff, ",
        "In the service request, ",
        "The internal note says: ",
        "For review only, ",
        "After the call, ",
        "In the latest update, ",
        "The requester added:\n",
    ),
    "validation": (
        "",
        "Kindly ",
        "This morning, ",
        "For the review desk, ",
        "A new request asks: ",
        "In the validation note, ",
        "Before close of business, ",
        "For compliance review, ",
        "The coordinator recorded: ",
        "During assessment, ",
        "For the client desk, ",
        "Within this request, ",
        "As the next action, ",
        "For next week's handover, ",
        "In the tracking ticket, ",
        "The review note states: ",
        "For confirmation only, ",
        "Following the meeting, ",
        "In the revised brief, ",
        "The analyst added:\n",
    ),
    "challenge": (
        "",
        "Would you ",
        "This afternoon, ",
        "For the response unit, ",
        "An incoming message says: ",
        "In the challenge note, ",
        "Before the next shift, ",
        "For the control check, ",
        "The specialist recorded: ",
        "During investigation, ",
        "For the delivery desk, ",
        "Inside this case, ",
        "As the final action, ",
        "For the upcoming transfer, ",
        "In the incident ticket, ",
        "The case note states: ",
        "For verification only, ",
        "After the briefing, ",
        "In the amended request, ",
        "The reviewer added:\n",
    ),
}


V2_SUFFIXES: dict[str, tuple[str, ...]] = {
    "train": (
        "",
        " Thanks.",
        " Please confirm.",
        " This is for testing.",
        " Reply when complete.",
        " Keep the wording concise.",
        " No action is urgent.",
        " Add the result to the ticket.",
        " Use the approved workflow.",
        " Finish before the demo.",
        "\nThen close the request.",
        "\nA short response is enough.",
        " Could you check?",
        " pls review.",
        " Do not change unrelated fields.",
        " Record only the outcome.",
        " The queue is waiting.",
        " Treat this as a routine task.",
        " Include a completion note.",
        " Let the account team know.",
    ),
    "validation": (
        "",
        " Thank you.",
        " Confirm the outcome.",
        " This is a validation exercise.",
        " Respond after completion.",
        " Keep the response brief.",
        " Normal priority applies.",
        " Attach the result to the review.",
        " Follow the standard procedure.",
        " Complete it before handover.",
        "\nThen mark the review complete.",
        "\nOnly a short note is required.",
        " Can you verify?",
        " pls validate.",
        " Leave other fields unchanged.",
        " Capture only the decision.",
        " The review desk is waiting.",
        " Handle this as routine work.",
        " Add a validation note.",
        " Notify the client desk.",
    ),
    "challenge": (
        "",
        " Much appreciated.",
        " Verify when finished.",
        " This belongs to the challenge run.",
        " Send a response afterward.",
        " Keep the answer compact.",
        " Process it at normal priority.",
        " Put the result in the case.",
        " Use the documented process.",
        " Complete it before shift change.",
        "\nThen resolve the case.",
        "\nA one-line note is sufficient.",
        " Would you verify?",
        " pls double-check.",
        " Do not edit other details.",
        " Save only the final status.",
        " The response unit is waiting.",
        " Treat this as standard work.",
        " Include a case note.",
        " Notify the delivery desk.",
    ),
}
